version: '2'
services:
  cloudera:
    image: cloudera/quickstart:latest
    privileged: true
    hostname: quickstart.cloudera
    command: > #command: /usr/bin/docker-quickstart  #
      bash -c "yum -y -t install --nogpgcheck ntp
      && service ntpd restart
      && sudo ntpdate -u 0.pool.ntp.org
      && /usr/bin/docker-quickstart  
      && /home/cloudera/cloudera-manager --express"
    ports:
      - '123:123' #ntp
      - '8020:8020' # HDFS
      - '8022:22' # SSH
      - '7180:7180' # Cloudera Manager
      - '8888:8888' # Hue
      - '11000:11000' # Oozie
      - '50070:50070' # HDFS Rest Namenode
      - '50075:50075' # HDFS Rest Datanode
      - '2181:2181' # Zookeeper
      - '8088:8088' # YARN Resource Manager
      - '19888:19888' # MapReduce Job History
      - '50030:50030' # MapReduce Job Tracker
      - '8983:8983' # Solr
      - '16000:16000' # Sqoop Metastore
      - '8042:8042' # YARN Node Manager
      - '60010:60010' # HBase Master
      - '60030:60030' # HBase Region
      - '9090:9090' # HBase Thrift
      - '8080:8080' # HBase Rest
      - '20550:20550' # HBase Rest
      - '8085:8085' #restServer web
      - '7077:7077' # Spark Master
    tty: true
    stdin_open: true
    volumes:
      - /tmp/shared_cloudera_quickstart:/media/shared_from_local
